### ISSUE TITLE
Fail to reproduce results

### ISSUE THREAD

**Issue by ytc272098215** [AnryYang/ACMin#2]
Hello, I cannot reproduce the results reported in the paper. The nmi of cora is reproduced as 0.007. I think I should have made a mistake, but I did not find an obvious mistake. Could you please confirm whether the public code of this version is still running correctly in your environment?

**Comment by ytc272098215** [comment]
> Hello, I cannot reproduce the results reported in the paper. The nmi of cora is reproduced as 0.007. I think I should have made a mistake, but I did not find an obvious mistake. Could you please confirm whether the public code of this version is still running correctly in your environment?

UPDATE: 
Hi, I have found the reason! 
I have modified the code to a py3 version so it goes wrong. But when I changed them back to the py2-based version according to your requirements, the nmi of core increase to 0.49 successfully!

**Comment by AnryYang** [comment]
> > Hello, I cannot reproduce the results reported in the paper. The nmi of cora is reproduced as 0.007. I think I should have made a mistake, but I did not find an obvious mistake. Could you please confirm whether the public code of this version is still running correctly in your environment?
> 
> UPDATE:
> Hi, I have found the reason!
> I have modified the code to a py3 version so it goes wrong. But when I changed them back to the py2-based version according to your requirements, the nmi of core increase to 0.49 successfully!

Thanks for your update.
